version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account_managment
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
    volumes:
      - .:/app # Monte le code local et donc quand on modifie en local, ça update le volume du container
    ports:
      - "8000:8000" # Map the internal port of the app to a host port
    depends_on:
      db:
        condition: "service_healthy"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: account_managment

volumes:
  db_data:
