# Generated by Django 5.1.2 on 2024-11-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("back_account_managment", "0005_alter_profile_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="back_account_managment.accountuser",
                    ),
                ),
                (
                    "permissions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
        ),
    ]
