# Generated by Django 5.1.2 on 2024-12-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("back_account_managment", "0008_item_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "permissions": [
                    ("link_user_item", "Can link a user to an item")
                ]
            },
        ),
    ]
