# Generated by Django 5.1.2 on 2024-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0011_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salary_based_split',
            field=models.BooleanField(default=False),
        ),
    ]
