# Generated by Django 5.1.2 on 2024-12-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0013_transfert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('link_user_item', 'Can link a user to an item'), ('add_item_without_user', 'Can create an item with no user'), ('transfert_item', 'Can transfert item into account')]},
        ),
    ]
