# Generated by Django 5.1.2 on 2025-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0020_delete_usercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='categories',
            field=models.ManyToManyField(through='back_account_managment.AccountCategory', to='back_account_managment.category'),
        ),
    ]
