# Generated by Django 5.1.2 on 2025-02-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0021_account_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='categories',
            new_name='account_categories',
        ),
    ]
