# Generated by Django 5.1.2 on 2025-02-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0023_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.JSONField(),
        ),
    ]
