# Generated by Django 5.1.2 on 2025-02-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0024_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_categories',
        ),
        migrations.DeleteModel(
            name='AccountCategory',
        ),
    ]
