# Generated by Django 5.1.2 on 2025-02-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0025_remove_account_account_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='categories',
            field=models.ManyToManyField(related_name='accounts', to='back_account_managment.category'),
        ),
    ]
