# Generated by Django 5.1.2 on 2025-02-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0026_account_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUserPermission',
        ),
    ]
