# Generated by Django 5.1.2 on 2025-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('back_account_managment', '0027_delete_accountuserpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
