# Generated by Django 5.1.2 on 2025-02-15 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_account_managment', '0029_alter_transfert_item_alter_transfert_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_user',
            field=models.ManyToManyField(related_name='accounts', through='back_account_managment.AccountUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
