# Generated by Django 5.1.2 on 2025-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_account_managment", "0030_account_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="object_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
